[WIP] Support for variable hover evaluation
puremourning/vimspector pull request #316
Opened 2020-12-10 04:36 UTC by dsych

**This is a work in progress**.
> Disclaimer: I know that you insist on specific code style so please disregard that for now. 
> Also, for the time being this only works with nvim. I have not migrated balloon expr to popup window for vim, but it should still work as expected.
> Both python and vim code is either not in the correct places or needs refactoring. I found this layout to be the easiest during debugging.

So having said that, here is the breakdown of this feature:
1. Added a function `vimspector#internal#state#ShowTooltip` that could be called to perform hover evaluation of a specific variable.
2. The float window **traps the cursor**. I saw your comment about this behaviour not being entirely desirable, so I am open to alternatives.
3.  In order to close the float window one can: just leave the window e.g. `<c-w>w`, close it as a regular window with `:quit`, `:close` etc., press `<esc>`
4. I tried using as much of the existing code as possible, so the variable rendering and expansion is calling into variable window's logic. No custom code is written for that piece.

#309

![Peek 2020-12-09 23-23](https://user-images.githubusercontent.com/16144679/101721898-0ab3b200-3a77-11eb-88a6-6c04be974468.gif)

2020-12-10 04:36 UTC, puremourning commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/puremourning/vimspector/316)
<!-- Reviewable:end -->

2020-12-10 15:27 UTC, dsych commented
@puremourning i guess what i am looking for here is some feedback on the general approach. do we want the cursor to be trapped, how is the expansion of variables, wrapping vs non-wrapping lines etc.

2020-12-10 16:01 UTC, puremourning reviewed
I don't really have an opinion on those things, because personally I don't love the way this works. The fact is that this will never work in Vim as it is, so I'm never going to use it. There is no way to "trap" the cursor in a popup in vim per se, and (while I fully admit that I haven't tried this out yet) I'm not sure I'd personally want to.

It would seem to me to not be very nice to have this big window appear in the middle of the screen that's kind of modal and interactive, when you already have that functionality in the Watch window. The idea of using the balloon was to get a quick look at the value of a variable; I wonder if this interactive popup is just "too much UI" ?

I'm not sure really. The main problem with features that only work in neovim is that they just don't get tested. There's no regression suite for neovim and I don't use it, so it's likely that I will accidentally break it or make it behave erratically when I change something unrelated. That's my main concern.

A thought occurs to me that might be a solution. Maybe there's a different way to go here, which is to refactor `variables.py` to allow for multiple "instances" of the "Watch" window (I did this for the Output window recently and it wasn't all that much work). We could then have an API that like said `vimspector#NewWatchWindow()` or perhaps `vimspector#MakeWatchWindow( window_id )`. This would:

* allow users to have multiple watch windows if they want that sort of thing (which I guess is useful)
* allow for some stuff _on top_ of that which neovim users can use to make a popup and turn it into a watch window, then use `vimspector#Watch( <expression> )` (we'd have to update that to take a target buffer/window id ?) to make the popup similar to your demo.

I realise that's a bit of a deviation from this implementation, but what do you think ? Does my reasoning make senes ?

> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316#-:-MOCLCwlCuMcn-A7yW1D:b71kojo)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-10 16:52 UTC, puremourning commented
Sorry I should say First and foremost: Thanks for sending a PR! I didn't mean to sound overly negative above, just mulling the ideas !

2020-12-14 03:55 UTC, dsych commented
Thanks for your reply. I needed to mention that this plugin is **AWESOME** and it finally convinced me to switch to vim full time for all my work. So big kudos for that. And because of this, I really want to get this plugin in as many hands as possible, since I believe it deserves the praise.

As for your actual comment, I completely understand your concerns about neovim's testability here, I also can't ask you to start supporting something that is not part of your use case. After all, this project is first and foremost the solution to **your** problem, and only after that a solution for the rest of us.

However, if you are going to accept contributions from the community, I think it is good to keep an open point of view. Other dev's workflows might be different from yours, so having a "big partly interactable piece of ui in the middle of the screen" might be desirable for them. Evidently, judging by the number of issues related to this feature for [vscode](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+debug+hover) (this is where I drew inspiration for this feature), quite a lot of people do find it useful.

 Anyway, I might have not been clear about my intentions for this feature. I never imagined it to be a neovim gimmick only. In fact, I was able to implement something similar for vim as well. Now that this feature is inside vim, too, we could easily create an integration test for it and that way you won't need to worry about accidentally breaking it. The only difference between the neovim and vim implementation is in the tooltip creation logic. Everything else is the same.

For the time being, I mapped the following keys for navigation inside the popup: 
j - down
k - up
esc - close
cr - expand
all the mouse navigation works except for double clicking for expand, for now. _You still can navigate the hover popup with keyboard._

NOTE: I kept the mouse hover logic similar to **beval**, meaning if mouse if moved, the popup will be closed. However, it does not need to be this way. We can hover with mouse and use double left click for variable expansion. In this case popup would need to be closed manually by clicking outside the popup or pressing <esc>.

Here is a small demo:
![Peek 2020-12-13 22-28](https://user-images.githubusercontent.com/16144679/102038437-41e6d380-3d95-11eb-8c72-dfd58e2c3458.gif)

2020-12-17 19:24 UTC, dsych commented
@puremourning ping

2020-12-17 19:36 UTC, puremourning commented
Sorry this is a big change so it gonna take a chunk of time to review and process. I did give this a go in vim and have some thoughts but I’m monster busy at the moment so haven’t had time to reply.

2020-12-17 19:38 UTC, dsych commented
sure no worries) i just did not know if you still wanted to proceed with this

2020-12-17 20:08 UTC, puremourning commented
I input trapping probably it needs to be initiated by the user rather than mouse hover. I don’t think mouse hover should trap keyboard input - that feels kinda wrong to me, but a mapping to do it feels better and more predictable. Then again once the hover is there, the double click feels natural and similar to other Interfaces i have used so it does seem an improvement on balloon. 

If we do trap keyboard, We probably then also want to trap _all_ input but that starts to get really hard (like I’m in the floaty buffer, what if I do `/abc`) etc.  Bram was very clear that he didn’t think there was a good use case for being able to ‘focus’ the popup window. Maybe we need to take this use case to vim_dev and ask what he thinks. I don’t feel comfortable trying to emulate that.

There were some other things like we need to get the rhyming right (eg set syntax) but also some way to differentiate the popup from the normal background and we need to probably think about the width and height of the popup a bit more. 

Those are just a few thoughts from what I remember. Wdyt?

2020-12-18 01:36 UTC, dsych commented
It definitely makes sense what you said about not trapping all keys. I thought about this and modelled this screen after the `:h popup_menu()` in terms of key bindings and **only in the normal mode**. I don't think we need to _focus_ the popup per say. Having rudimentary navigation should be sufficient. _Maybe_ a search but that is it. I am not sure that can even be done, honestly, since popups are so very limited.

As for the keyboard trapping on hover, we can turn that off easily, but that would leave popup equivalent to balloon and what is the point of that. I also mentioned a possibility of **not closing popup when mouse if moved**. This will allow us to properly implement double clicking on the popup items to expand them. However, this also means that we would need to close the popup manually by clicking somewhere off the popup area.

We could add popup border in order to differentiate it from surrounding code. Admittedly, it is hard to spot it from the get go.

I have not really though about the popup dimensions... We can set min/max values for width and height thought. During my testing, I found that we need at least 3 lines to accommodate for long template types in c++. On the other hand, 5 lines seems to be the max number of lines I could tolerate without popup being too distracting. You still want to see the code that is being evaluated after all...

2020-12-22 16:15 UTC, puremourning commented
testing a bit more, I think while in some cases we have "more is better" (such as structured data), we seem to have lost some clarity for _simple_ data:

WItht the "popup containing a watch window":

![Screenshot 2020-12-22 at 16 13 51](https://user-images.githubusercontent.com/10584846/102909308-afb78d00-4470-11eb-8b53-87653f9b4a7b.png)

Compare with the simple balloon:

![Screenshot 2020-12-22 at 16 14 44](https://user-images.githubusercontent.com/10584846/102909390-cf4eb580-4470-11eb-9584-3d99cad2bd7b.png)

This is probably solvable just in the presentation, but worth thinking about.

2020-12-22 16:34 UTC, puremourning commented
for the record, I'm not completely against keeping the "balloon" version for mouse-hover and adding the popup version for some mapping or function call like you would need in neovim anyway.

E.g.:

* Mouse hover = simple version with no interaction
* call `vimspector#GetSymbolInfo()` or something opens the popup version
* maybe a default mapping (TBD: need to check what common IDEs use) to pop the popup

Does that lead to too many ways to do the same thing ? And maybe non-discoverable interface? It's certainly tricky to know what the right UI/UX is here !

BTW: the if the mouse enters the popup, then it is not dismissed, so the double-click-to-expand _should_ work, which I think lends itself to _not_ trapping the keyboard input at all during the popup, only the mouse. This would be consistent with how typical UIs handle this popup/popover.

2020-12-22 17:34 UTC, puremourning commented
tried this in neovim 0.4 and it doesn't seem to work :(

is this relying on features in neovim master?

2020-12-22 18:05 UTC, dsych commented
My bad, I was using `:h literal-Dict" in nvim portion of the script and did not realize that is was only available on master. It is fixed now.

2020-12-22 18:09 UTC, dsych commented
> testing a bit more, I think while in some cases we have "more is better" (such as structured data), we seem to have lost some clarity for _simple_ data:
> 
> WItht the "popup containing a watch window":
> 
> ![Screenshot 2020-12-22 at 16 13 51](https://user-images.githubusercontent.com/10584846/102909308-afb78d00-4470-11eb-8b53-87653f9b4a7b.png)
> 
> Compare with the simple balloon:
> 
> ![Screenshot 2020-12-22 at 16 14 44](https://user-images.githubusercontent.com/10584846/102909390-cf4eb580-4470-11eb-9584-3d99cad2bd7b.png)
> 
> This is probably solvable just in the presentation, but worth thinking about.

In you example, I think there is a bug in my code that displays type information as it appears to be empty for simple types.
On the other hand, it seems to me like we are wasting a lot of space with labels like "Type:" and "Value:" in the regular balloon. This would become especially apparent with nested types.

2020-12-22 18:30 UTC, puremourning commented
> we are wasting a lot of space with labels like "Type:" and "Value:" in the regular balloon. This would become especially apparent with nested types.

Perhaps, but I can actually read the balloon version and quickly see the thing I want to know (the value of the scalar variable). For the single-line version I have to parse the output.

There's also non-data ink in the "change" marker and the "bullet point" (`. * - `) and the repeating of the expression (`t._var`).

2020-12-22 18:54 UTC, dsych commented
> for the record, I'm not completely against keeping the "balloon" version for mouse-hover and adding the popup version for some mapping or function call like you would need in neovim anyway.
> 
> E.g.:
> 
>     * Mouse hover = simple version with no interaction
> 
>     * call `vimspector#GetSymbolInfo()` or something opens the popup version
> 
>     * maybe a default mapping (TBD: need to check what common IDEs use) to pop the popup
> 
> 
> Does that lead to too many ways to do the same thing ? And maybe non-discoverable interface? It's certainly tricky to know what the right UI/UX is here !
> 
> BTW: the if the mouse enters the popup, then it is not dismissed, so the double-click-to-expand _should_ work, which I think lends itself to _not_ trapping the keyboard input at all during the popup, only the mouse. This would be consistent with how typical UIs handle this popup/popover.

I would argue that having at least some sort of interaction inside a hover popup should be present to accommodate for nested types. I believe, this is what other gui debuggers are doing.
I agree that we might have different ways to interact with the popup, but the underlining code should not be different. This would add unnecessary maintenance overhead...

2020-12-22 18:54 UTC, dsych commented
my bad, wrong button)

2020-12-22 18:56 UTC, dsych commented
> > we are wasting a lot of space with labels like "Type:" and "Value:" in the regular balloon. This would become especially apparent with nested types.
> 
> Perhaps, but I can actually read the balloon version and quickly see the thing I want to know (the value of the scalar variable). For the single-line version I have to parse the output.
> 
> There's also non-data ink in the "change" marker and the "bullet point" (`. * - `) and the repeating of the expression (`t._var`).

Makes sense. I will look into shortening this message. How about `(type): value`?

2020-12-22 18:59 UTC, dsych commented
I removed keyboard trapping from mouse hover window and added support for double click to expand. However, you need to **click** outside the popup in order to close. Please see how you feel about that.

2020-12-23 05:09 UTC, dsych commented
I have added support for border and have to admit that it looks a lot better with it. Oh, and this is also showcasing double click to expand. As you can see, in order to close the popup, we need to click somewhere else or hover over another piece of text.

### Vim
![Peek 2020-12-23 00-04](https://user-images.githubusercontent.com/16144679/102961655-dc8c9400-44b2-11eb-9eca-4b8404b302ed.gif)

### Nvim
![Peek 2020-12-23 00-06](https://user-images.githubusercontent.com/16144679/102961661-e31b0b80-44b2-11eb-82f1-e72436ebbc06.gif)

2020-12-23 11:20 UTC, puremourning commented
Nice. Getting there I think.

Something seems off though. Trying out java test app, I find this is useful:

![Screenshot 2020-12-23 at 11 20 36](https://user-images.githubusercontent.com/10584846/102991311-e2b15d80-4510-11eb-82e8-d6da66184c22.png)

But, just hovering on a simple string gives confusing result, whereas evaluating it in the watch window is much simpler. Are we missing the result of the evaluation and only printing the "breakdown" ?

![Screenshot 2020-12-23 at 11 19 00](https://user-images.githubusercontent.com/10584846/102991184-aaaa1a80-4510-11eb-9f80-042fc4b11dd4.png)

2020-12-23 11:25 UTC, puremourning commented
Also the buffer in neovim is modifiable!

2020-12-23 11:26 UTC, puremourning commented
I'm really starting to like this btw. Thanks so much for the hard work.

2020-12-23 19:19 UTC, dsych commented
> Also the buffer in neovim is modifiable!

I know... Tried making it read only, but the logic for rendering variables is **appending** content to the buffer. This is treated as modification and is not allowed.
We could turn on the modification for the time of rendering and toggle it off once done, however that seems like unnecessary hassle to me. Maybe I am wrong.. What do you think?

2020-12-23 19:48 UTC, puremourning commented
The python code has `with ModifyableScratchBuffer()` for this.

2020-12-24 05:15 UTC, dsych commented
1. Fixed the buffer type in nvim, now it is not modifiable.
2. Removed the variable name for simple types.
3. Fixed variable type not being displayed for simple types.
4. **Limited the length of variable type and value** to 20 and 100 respectively. This is done to accommodate for the small size of the popup and the use case it is solving. Since it is supposed to be a quick way to check the variable value, the type is not really all that relevant. Should the user require a more comprehensive view of the given variable, there is the watch window and the variables window.

I am curious to hear your thoughts on number 4. I arbitrarily picked the lengths, so they can definitely be adjusted.

![Peek 2020-12-24 00-05](https://user-images.githubusercontent.com/16144679/103062686-ebd81400-457c-11eb-940d-5d6b18b8f39d.gif)

2020-12-24 12:37 UTC, puremourning commented
There's still a problem with the basic value display. Take this `std::string`:

With the balloon hover:

<img width="708" alt="Screenshot 2020-12-24 at 12 24 18" src="https://user-images.githubusercontent.com/10584846/103088563-19f03f00-45e3-11eb-9169-84854ace5ff1.png">

WIth this version:

<img width="794" alt="Screenshot 2020-12-24 at 12 20 28" src="https://user-images.githubusercontent.com/10584846/103088572-207eb680-45e3-11eb-8957-97fe84bac52f.png">


And for primitive values, we're still displaying a lot of non-data ink:

<img width="279" alt="Screenshot 2020-12-24 at 12 18 21" src="https://user-images.githubusercontent.com/10584846/103088599-35f3e080-45e3-11eb-9568-6a9059362cbd.png">

---

Regarding the sizing, it's really tricky. I think when it wraps it looks bad and really hard to follow (I disabled wrapping in the watch window a while back for this reason). I made a couple of edits and it think it works well to:

* disable wrapping
* Allow to drag the popup to resize and move it

try this patch

```
diff --git a/autoload/vimspector/internal/balloon.vim b/autoload/vimspector/internal/balloon.vim
index 467de90..9a6e1af 100644
--- a/autoload/vimspector/internal/balloon.vim
+++ b/autoload/vimspector/internal/balloon.vim
@@ -127,6 +127,7 @@ function! vimspector#internal#balloon#CreateTooltip(is_hover, ...)
   else
     " assume we are inside vim
     func! MouseFilter(winid, key)
+      let handled = 0
       if index(["\<leftmouse>", "\<2-leftmouse>"], a:key) >= 0
         let mouse_coords = getmousepos()
         " close the popup if mouse is clicked outside the window
@@ -142,11 +143,10 @@ function! vimspector#internal#balloon#CreateTooltip(is_hover, ...)
           " forward line number to python, since vim does not allow us to focus
           " the correct window
           call py3eval("_vimspector_session.ExpandVariable(".line('.', a:winid).")")
+          let handled = 1
         endif
-
-        return 1
       endif
-      return 0
+      return handled
     endfunc

     func! CursorFiler(winid, key)
@@ -175,17 +175,19 @@ function! vimspector#internal#balloon#CreateTooltip(is_hover, ...)

     let config = {
       \ 'cursorline': 1,
-      \ 'wrap': 1,
       \ 'filtermode': "n",
       \ 'maxwidth': max_width,
       \ 'maxheight': max_height,
       \ 'scrollbar': 1,
-      \ 'border': []
+      \ 'border': [],
+      \ 'wrap': 0,
       \ }
     if a:is_hover
       let config['filter'] = "MouseFilter"
       let config['mousemoved'] = [0, 0, 0]
       let config['close'] = "button"
+      let config['drag'] = 1
+      let config['resize'] = 1
       let s:float_win = popup_beval(body, config)
     else
       let config['filter'] = "CursorFiler"
```

2020-12-24 14:03 UTC, puremourning commented
I have asked users in the Gitter channel to try this PR out and leave feedback here.

2020-12-25 04:36 UTC, dsych commented
There is a problem with disabling wrapping for vim's popup window, if you are not using mouse. There is no 'real' cursor inside that window, which means that there is no way to scroll to the side. Consequently, should your data be sufficiently long, you won't be able to see the end of it regardless of how big the popup window is.
Due to the point above, I enabled wrapping in the popup. However, now we have a different kind of problem. A single variable might be wrapped longer than the size of the popup. Hence, the proposed change to limit the size of the type and value strings.

2020-12-25 09:02 UTC, puremourning commented
I was able to scroll with the mouse wheel I think.

2020-12-25 18:17 UTC, dsych commented
Sorry if I was not clear. What I mean is that you can't scroll to the right or left with vim's popup. E.g.
Window width is 10 columns. If the text is `some looooooooooooooooong text`, than we are not going to see the end of the text. It will look something like this:
`some loooo` <- 10 columns, while the rest of the text is truncated.

2020-12-26 09:51 UTC, puremourning commented
Related https://github.com/vim/vim/pull/7555

2020-12-31 05:53 UTC, dsych commented
I have been following the PR you linked and Bram mentioned one very relevant point:
> Regardless of how popup window is reworked, the user adoption is going to be slow.

So, if we hope to have this hover eval feature merged, we need to not rely on the vim's patch to be merged. Hence, I am suggesting an incremental upgrade strategy.

We are to introduce a new configuration variable, `g:vim_popup_appearance`, which will control the appearance of the popup for vim only. Nvim will not be affected by this. 

Possible values are the following:
1. `0` - default if user is running vim with the popup upgraded. This popup is **not wrapped** and user can scroll lines horizontally to view hidden text.
2. `1` - fallback default if user is missing enhanced popup window. In this case, **lines are wrapped**, plus `value` and `type` length is restricted. The length is subject to debate.
3. `2` - optional value. In this case, **lines are wrapped**, but `value` and `type` have unrestricted length. This is mostly to allow users to have a choice if they wish to see all the info, but with caveat of possibly not being able to fit the text inside the popup ( think c++ templates).

With this approach, we are still going to move forward with this feature allowing people to start using it. Once the new popup window is available in stable vim, we would revisit this PR and probably refactor the vim's implementation to resemble the one of nvim more closely (depending if the popup does become a regular window or not).

2020-12-31 10:00 UTC, puremourning commented
yes we can move forward without the vim change, but it helps to have a vision of the future so we know what we can/should do now. 

We should avoid behavioural options and just do the right thing. Options are a tax on development and maintenance and even worse they are a tax on the user who has to understand them and read the manual (which is already a significant burden for most users). 

I’m quite strongly against wrapping in these windows. Honestly, the watch window wrapped for ages and it just drove me mad, so I would rather that you just have to use the watch window if you can’t see the value if it is too long. 

I think the more important things to work on now are the presentation. Minimise
The non data ink and include the actual evaluated value (see my std string case above). I think that will be a big improvement. 

Mouse support for drag and resize like in my suggested patch works well for the balloon mouse hover. There is currently no keyboard-only trigger for this in vim so we could elect not to implement that yet. And when/if there is a vim feature we can exploit, add that then. 

For neovim keyboard only is the only option and so is therefore using a normal window. 

I think that’s probably enough for one PR :)

orher things that need doing:

- coding standards/styles 
- I don’t like having if neovim here and there; prefer to match the may it’s down elsewhere if possible. 
- tests
- Docs

2020-12-31 17:31 UTC, dsych commented
Fair enough. I am going to disable wrapping and incorporate your patch for hover popup. 

Moreover, I just realised that we don't actually need to display the type information inside the eval window. So I am thinking to use the same format vscode is using, which is `* - name: value` for nested types and `value` for simple types.
What do you think?

2020-12-31 18:14 UTC, puremourning commented
I don’t think we need the ‘*’; this is a change marker and they will always have just changed. 

Let’s try without the type in a number of languages and see how it feels.

2021-01-02 21:06 UTC, dsych commented
A couple of quality of life improvements from the recent patch:
1. enabled dragging and resizing.
2. implemented dynamic sizing of nvim's float window to mimic vim's popup (finally)
3. shortened the information inside the tooltip to `+ name: value` and `value` for nested and simple types, respectively. as you suggested, i removed all of the cruft around simple types. See examples below.

I eagerly await your feedback. The current state of things looks to me like something we would want to keep.

![Screenshot from 2021-01-02 15-58-38](https://user-images.githubusercontent.com/16144679/103466585-583cdb00-4d14-11eb-9893-17b487290a28.png)
![Screenshot from 2021-01-02 15-57-58](https://user-images.githubusercontent.com/16144679/103466587-58d57180-4d14-11eb-83d1-136a0792adda.png)
![Screenshot from 2021-01-02 15-57-30](https://user-images.githubusercontent.com/16144679/103466588-58d57180-4d14-11eb-8539-c5e3ca81709b.png)

2021-01-05 21:35 UTC, puremourning commented
been playing with this a bit today. will put up some more feedback soon. thanks for the continued effort on this!

must admit that now I know this exists I keep reaching for it and in versions of vimspector where it's not there I do miss it. I still think there's work to be done on usability, but it's certainly getting there!

2021-01-05 22:14 UTC, puremourning commented
Made some tweaks while playing with it:

1. Store a `Watch` as the hover expression and use the existing `_DrawWatchResult` to draw it
2. Set `result.expanded = EXPANDED_BY_US` to always expand the first level of the result 
3. Enable syntax highlighting in the popup
4. Increase the maximum width and height to 80x20
5. Fix mouse drag and resize

[![asciicast](https://asciinema.org/a/yyPpaQShNPHXWkRx6a9hVGCK5.svg)](https://asciinema.org/a/yyPpaQShNPHXWkRx6a9hVGCK5)

WDYT


Changes here: https://github.com/puremourning/vimspector/commits/nvim-float-window

2021-01-05 22:59 UTC, dsych commented
I completely agree with all the points accept for the first one that replaces Variable drawing with Watch drawing. It seems to me like we fought to decrease the amount of clutter on the screen to make output be easily parsable and this is a step back. The `Expression ....` seems to be a little bit redundant.
I actually rather liked the simplicity of the view that I presented before.

There is one really cool feature we could implement that would justify the Watch drawing - allow for evaluation of expressions based on visual selection. E.g.
```c++
int a = 5, b = 6;
char c = 'p';
int rc = a + b + c;
```
The user could visually highlight `a + b` on line 3 and then call our function that could evaluate the expression and give the result. In this case, it seems appropriate to display the `Expression ...` message.

2021-01-06 10:00 UTC, puremourning commented
> one really cool feature we could implement

I believe that this already works. If you make a visual selection and hover on it, that's the expression that gets evaluated. At least that's the case with the original balloon, and why I thought this was appropriate.

I found the display of "just the value" harder to read if I'm honest. I added the padding to help separate it from the border, but I somehow found it jarring.

I'll think on it a bit more.

2021-01-06 10:11 UTC, puremourning commented
For the record the storing of a 'Scope' and hacking the result array is not really art, so using a Watch is certainly the way to go, however we draw it.

2021-01-06 14:08 UTC, dsych commented
> For the record the storing of a 'Scope' and hacking the result array is not really art, so using a Watch is certainly the way to go, however we draw it.

I second that. Never really liked how I needed to hack the Scope and View in place. This seems VERY fragile and prone to breaking whenever code that uses it changes. So I am all for switching to Watch window if that is more maintainable ( especially since you already did most of the work) )

Anyway, the point I was trying to make is that we should tweak the **drawing of the watch**. Maybe introduce a **short** version of the output the same way I did for Variables window.

> The Expression .... seems to be a little bit redundant.

I guess this is more of my personal preference than anything else. It seemed to me that you shared my sentiment as indicated by your previous comments.

It really is a shame that nobody else from the community gave their perspective on this. We could really use a third opinion. However, in the absence of it, maybe we can take a look at how other IDEs are drawing hover? 
For instance, this is how VScode does it:
![Screenshot from 2021-01-06 09-04-16](https://user-images.githubusercontent.com/16144679/103777041-51f17c00-4ffe-11eb-84e0-5975e7045093.png)
They indicate the `type` in the header and the content is in the form of `is_expanded name: value`

What do you think?

2021-01-06 14:35 UTC, puremourning commented
In that screenshot, it looks to me like the evaluate result is at the top, then a line, then the "first level" expansion of the value, which is sort of a combination of what I put and what you put. We can try that, see how it feels (we can't draw a horizontal line easily to my knowledge, but we can just indent the expansion).

Something like this:

[![asciicast](https://asciinema.org/a/6cSgYXSM8he4zwphdMeKx2vCf.svg)](https://asciinema.org/a/6cSgYXSM8he4zwphdMeKx2vCf)

(pushed this version to origin/nvim-float-window)

>  shame that nobody else from the community gave their perspective on this

I think when we're happy-ish with it, or have like a specific set of options, it will be easier to get feedback. Asking a group of busy people to test some random change doesn't usually yield great results in my experience, but asking for an opiion on a few specific options usually gets more results. It's also a good opportunity to boost your reddit karma :)

2021-01-06 14:45 UTC, puremourning commented
This is what it looks like for a struct

<img width="825" alt="Screenshot 2021-01-06 at 14 44 01" src="https://user-images.githubusercontent.com/10584846/103780973-a06a3f00-502d-11eb-864a-5e50c1714b7c.png">

And for a scalar:

<img width="329" alt="Screenshot 2021-01-06 at 14 44 38" src="https://user-images.githubusercontent.com/10584846/103781039-b4ae3c00-502d-11eb-9fb3-0185625e10e0.png">

And for a std::string in this debug adapter:

<img width="364" alt="Screenshot 2021-01-06 at 14 45 05" src="https://user-images.githubusercontent.com/10584846/103781083-c4c61b80-502d-11eb-9532-81d1bc1bc483.png">

I think it's a nice combo?

2021-01-06 15:10 UTC, puremourning commented
yeah, I really like the latest iter:

* use a "short" display mode for `_DrawWatchResult` that gets rid of some stuff
* Disable `cursorline` in the hover-only version of the popup

I tried it out on java, tcl, python, c++; it looks and feels right in all of them.

nice.

2021-01-06 15:11 UTC, dsych commented
> This is what it looks like for a struct
> 
> <img alt="Screenshot 2021-01-06 at 14 44 01" width="825" src="https://user-images.githubusercontent.com/10584846/103780973-a06a3f00-502d-11eb-864a-5e50c1714b7c.png">
> 
> And for a scalar:
> 
> <img alt="Screenshot 2021-01-06 at 14 44 38" width="329" src="https://user-images.githubusercontent.com/10584846/103781039-b4ae3c00-502d-11eb-9fb3-0185625e10e0.png">
> 
> And for a std::string in this debug adapter:
> 
> <img alt="Screenshot 2021-01-06 at 14 45 05" width="364" src="https://user-images.githubusercontent.com/10584846/103781083-c4c61b80-502d-11eb-9532-81d1bc1bc483.png">
> 
> I think it's a nice combo?
> 
> But maybe we should disable `cursorLIine` in the mouse-hover version of the popup:
> 
> <img alt="Screenshot 2021-01-06 at 14 46 56" width="509" src="https://user-images.githubusercontent.com/10584846/103781275-0787f380-502e-11eb-8778-8ecc910ec5c2.png">
> 
> <img alt="Screenshot 2021-01-06 at 14 47 13" width="829" src="https://user-images.githubusercontent.com/10584846/103781312-11115b80-502e-11eb-9c95-3a369caa40b9.png">
> 
> <img alt="Screenshot 2021-01-06 at 14 47 37" width="319" src="https://user-images.githubusercontent.com/10584846/103781342-1f5f7780-502e-11eb-9a0d-e0eae25234bd.png">

I love this. I will take your branch and disable the `cursorLine` for mouse popup.

After this, I think it is time to stop tweaking the presentation and start writing tests, docs etc. I want to finally ship this in the stable release and start using all the latest feature of vimspector (right now i am forced to patch my install with custom code...).

Anyone who does not like the presentation can file an issue later)

2021-01-06 15:13 UTC, puremourning commented
> Anyone who does not like the presentation can file an issue later)

👍

2021-01-06 15:24 UTC, puremourning commented
My hack for enabling syntax highlithging in the popup doesn't actually work properly btw. need to look into that (I just put some dodgy placeholder code there)

2021-01-07 05:18 UTC, dsych commented
You mentioned that mouse hover works on visual selection already, so I tried the same thing with function call. As you would expect, it did not work. So I spent way too much time getting this to work and this is the result.

Apparently, there is no direct way to get current visual selection boundaries inside a function call, since once you switch to command mode, we are dropped to normal mode and cursor is moved to the beginning of current line. The only option I found was using a mapping, which would to reset the visual selection, consequently allowing us to retrieve the visual selection boundaries. While we will probably do something like that, I wanted to make this work for regular function call as well.

Anyway, I ended up introducing a new function called `ShowTooltipForSelection()`. This function can be invoked on a range and it would be able to correctly calculate the visual selection (though some trickery) even for multi-line expressions (!).

![Peek 2021-01-07 00-08](https://user-images.githubusercontent.com/16144679/103854137-c0295380-507d-11eb-8341-ad5c1bc523d7.gif)

2021-01-07 08:07 UTC, puremourning commented
The solution is to make a command with ‘command -range’

2021-01-07 08:30 UTC, puremourning commented
Wait no you are right. that would be linewise. You have to use the ‘< and ‘> marks. 

I think we do this neatly in YCM for YcmCompleter Format. I’ll check what we do there.

2021-01-08 21:17 UTC, puremourning commented
FWIW, this is what we do in YCM:

1. Use a command with a range: https://github.com/ycm-core/YouCompleteMe/blob/master/autoload/youcompleteme.vim#L1170-L1175
2. _also_ use the marks when a range has been supplied: https://github.com/ycm-core/YouCompleteMe/blob/master/python/ycm/vimsupport.py#L1226-L1234

2021-01-08 21:33 UTC, puremourning commented
OK I'm really loving this change behaviour now. Using it to debug vimspector!

<img width="804" alt="Screenshot 2021-01-08 at 21 33 35" src="https://user-images.githubusercontent.com/10584846/104066343-2c7c9200-51f9-11eb-9b01-327b4d4f24cf.png">


I do think we need to set a much bigger maximum size for the popup. I set it to 80x20 and that feels about right to me. It's only the maximum, so we can be generous.

2021-01-08 21:59 UTC, puremourning commented
I quite like the borders you're using in the neovim popup, though I'm not a fan of the amount of code that's required to do it.

I implemented the same thing for vim:

```viml
    if &ambiwidth ==# 'single' && &encoding == 'utf-8'
      let config['borderchars'] = [ '─', '│', '─', '│', '╭', '╮', '╯', '╰' ]
    endif
```

In reading the help for borderchars, it made me think to check what happens with `ambiwidth=double` in neovim:

<img width="819" alt="Screenshot 2021-01-08 at 21 56 19" src="https://user-images.githubusercontent.com/10584846/104068161-597e7400-51fc-11eb-8601-6b9d25694354.png">

Yeah, need to avoid the ambiguous width characters there :)

Pushed a few commits to origin/nvim-float-window

2021-01-08 22:47 UTC, puremourning commented
Interestingly I managed to crash neovim by doing `:lopen` within the popup. :/

2021-01-08 23:06 UTC, puremourning commented
btw sometimes the 2 windows in neovim draw in different places

![Uploading Screenshot 2021-01-08 at 23.06.18.png…]()

2021-01-08 23:13 UTC, dsych commented
> btw sometimes the 2 windows in neovim draw in different places
> 
> <img alt="Screenshot 2021-01-08 at 23 06 18" width="702" src="https://user-images.githubusercontent.com/10584846/104073691-3d7fd000-5206-11eb-835d-3f42c60e43a0.png">

Is there anything specific you did that might have caused this? E.g. in the screen shot i can a see a prompt inside the float window.

2021-01-08 23:15 UTC, puremourning commented
> Is there anything specific you did that might have caused this?

I think I just opened it very close to the bottom of the screen. I'm guessing that neovim is shifting the windows to keep them on the screen, but due to the different sizes, it's shifting them different amounts.

2021-01-08 23:19 UTC, dsych commented
> > Is there anything specific you did that might have caused this?
> 
> I think I just opened it very close to the bottom of the screen. I'm guessing that neovim is shifting the windows to keep them on the screen, but due to the different sizes, it's shifting them different amounts.

Unfortunately, I dont think there is anything that could be done about that as of right now. The way border is implemented is already **very** hacky. I did not expect it to work every time...

Do you think it is that big of a deal to spend time investigating? I would much rather wait until nvim supports borders natively and then revisit this.

2021-01-09 00:11 UTC, puremourning commented
> would much rather wait until nvim supports borders natively and then revisit this.

Agree, though I would rather not have the border at all in neovim if we can't implement it simply and well. The extra complexity and the amount of code make it tenuous to start with, then it not always working suggests to me that it might be better without. In general, I'd rather not have a feature than have a buggy one. I'm reliably told that there's a very real chance that neovim will have the vim API supported at some point, at which time we can get a border in neovim.

I'll ask the neovim guys if there's a better way.

2021-01-09 00:25 UTC, puremourning commented
FYI : https://github.com/neovim/neovim/issues/13721

2021-01-09 10:59 UTC, puremourning commented
Ugh, just found another thing that is dodgy with 'focusable' floats in neovim: you can use `<Ctrl-w>L` to make the window into a normal split. This leads to this:

<img width="971" alt="Screenshot 2021-01-09 at 10 56 50" src="https://user-images.githubusercontent.com/10584846/104089763-62595f00-5269-11eb-951e-b3d4332faaae.png">

I am informed that this is intentional neovim behaviour, but for us it seems kinda dodge. I'm beginning to think Bram was right about having focusable popups is a bit of a bug factory.

2021-01-09 11:21 UTC, puremourning commented
I guess there are quite a few things a user could do in the neovim popup that make this kind wonky:

* Ctrl-w [HJKL]
* Ctrl-w + (etc. resize)

TBH I think you're right' we just have to live with this, unless we add a ton of buffer-local mappings to `<Nop>` and stuff. I'm not sure it's worth it. There was a suggestion that window option could be added like `opt.fixed` or `opt.locked_position`, but not holding breath.

I checked about the border and it does seem that it's the only way to do it, so I guess we just go with it. Neovim support is experimental anyway, so maybe I shouldn't worry too much about the polish.

2021-01-09 11:23 UTC, puremourning commented
I pushed some more commits https://github.com/puremourning/vimspector/commits/nvim-float-window

2021-01-10 20:09 UTC, dsych commented
I checked the commits you pushed and here are a couple of things I wanted to mention:
1. I added a close button for keyboard triggered popup, since we already allow drag and resize. Just to make sure that we are not missing out on functionality.
2. I do want to debate about the change to `Normal` highlighting for popup. It actually made it harder for me to spot where the cursor was in the vim's popup, since there is no actual cursor to begin with. I suggest that we put back the cursor line highlight. See the screenshot below.

![image](https://user-images.githubusercontent.com/16144679/104133966-eb999000-5354-11eb-8be1-e1358743aba9.png)

The variation in colour is too subtle, in my opinion. I am not colour blind and even I have trouble spotting where the cursor is from afar. I actually need to lean in a little bit. I think it just hurts the user experience.

However, that might be just my colour scheme's fault. I think the best solution here would be to expose the window id as a global variable, the same way that other windows are, and let the user decide if they want to update it.

**I would advocate for the old highlight as default, thought.**

2021-01-10 20:15 UTC, puremourning commented
> I would advocate for the old highlight as default, thought.

Agreed. It looks like he CursorLine highlight [always uses the PmenuSel highlight](https://github.com/vim/vim/blob/master/src/popupwin.c#L632-L635) even if you said the window to Normal highlight (rather than PMenu). It will be heavily dependent on colour schemes whether Normal + PMenuSel will look sane.

You make a good point about customisation, but let's not focus on any customisation API until we're stable on the implementation. Making an API is a decision we can't unmake. For now, let's do as you say - use the defaults, which should work everywhere.

2021-01-10 20:47 UTC, dsych commented
I want to start writing tests for this, but I need your help. What kind of tests would you find acceptable? Do you want a full unit test suite or just a couple of integration or both?

2021-01-10 21:42 UTC, puremourning commented
It will need full test coverage for the Vim functionality. Tests are "integration" in the sense they test what the user does; I don't care about "unit" tests in the sense that  just test code does what the author intended.

Relevant examples are https://github.com/puremourning/vimspector/blob/master/tests/variables.test.vim and https://github.com/puremourning/vimspector/blob/master/tests/ui.test.vim

Resources:

* https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#running-the-tests-locally
* I ported this test suite to YCM and it has better docs: https://github.com/ycm-core/YouCompleteMe/tree/master/test#overview

2021-01-10 21:44 UTC, puremourning commented
Should I start reviewing the code now? Is it in the "final" format (refactor and/or style wise) ?

2021-01-10 22:28 UTC, dsych commented
> Should I start reviewing the code now? Is it in the "final" format (refactor and/or style wise) ?

Yes, let's do this)

2021-01-10 23:40 UTC, dsych commented on python3/vimspector/variables.py
> +  def _DrawVariables( self, view, variables, indent, is_short = False ):
I will revert this function to its original state

2021-01-15 05:40 UTC, dsych commented on tests/variables.test.vim
> +  call win_execute( g:vimspector_session_windows.eval, 'call feedkeys( "\<Esc>", ''xt'')')
for some reason i am not able to feed `Esc` key to the popup window. it gives `E994` error (operation is not allowed). i tried using a regular `x` to close the window, but that seems to have the same effect. any other key works just fine, so it seems the problem is tied specifically to the keys that are supposed to close the window.

any clue why this happening?

2021-01-15 13:53 UTC, dsych commented on tests/variables.test.vim
> +  call win_execute( g:vimspector_session_windows.eval, 'call feedkeys( "\<Esc>", ''xt'')')
i read you article, but somehow i did not put 2 and 2 together about feedkeys modifying the global typehead. anyway, the problem seems to be fixed once i remove `win_execute` call. still, i wonder what function is called by `popup_filter_menu` that would trigger this error on `esc`

2021-01-16 04:13 UTC, dsych commented on python3/vimspector/variables.py
> +  def _DrawVariables( self, view, variables, indent, is_short = False ):
nvm, i didn't notice it was used inside `_DrawWatchResult`. not going to touch this.

2021-01-16 04:19 UTC, dsych commented
i have pushed some test cases that should suffice. please let me know if you want anything else to be tested.
once thing i have not done is write integrations for the mouse. however, i have not seen it being tested for watch and variables views, either.

2021-02-03 22:11 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: 0 of 7 files reviewed, 39 unresolved discussions (waiting on @dsych)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_5kf4-wveUC41fnB:-MSd_5kf4-wveUC41fnC:b4s52m) (no related file):*
(throughout) viml coding style needs to match the rest, i.e. spaces inside parens, brackets etc.

* `[ start, end ]`
* `[ [ line( "...`
* lines <= 80 characters

---
*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdwmA-5EggMupJlmF6:-MSdwmA-5EggMupJlmF7:bpg76v) (no related file):*
let's remove dead code for the old ballloon eval

---
*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdwpoq8cxKfz0FiCeX:-MSdwpoq8cxKfz0FiCeY:bse182y) (no related file):*
let's split the neovim and vim code in a similar way to the other code

---
___
*[autoload/vimspector.vim, line 526 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdaGvT2bZg4lQRzMCQ:-MSdaGvT2bZg4lQRzMCR:b4xmm5u) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L526)):*
> ```vim
> endfunction
> 
> function! vimspector#ShowTooltipForSelection() range abort
> ```

I think a lot of this would be easier to write in Python. We can make a function in `utils.py`. Something like this " 

```
def GetVisualSelection():
  if vim.eval( 'mode()' ) != 'v':
    raise ValueError( "Only available in visual mode" )
  
  start_line, start_col = vim.current.buffer.mark( "'<" )
  end_line, end_col = vim.current.buffer.mark( "'>" )

  assert start_line >= end_line

  lines = vim.buffers[ bufnum ][ start_line : end_line + 1  ]
  lines[ 0 ] = lines[ 0 ][ start_pos : ]
  lines[ -1 ] = lines[ -1 ] : end_pos + 1 ]
```
___
*[autoload/vimspector.vim, line 530 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_O8P5rcbkJ4-ktJt:-MSd_O8P5rcbkJ4-ktJu:b-iar97x) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L530)):*
> ```vim
>   " restor cursor position, since command mode puts it to the begining of the
>   " current line when invoked from visual mode
>   call cursor(end)
> ```

I'm not sure about this. I think it would be  to create a `<plug>VimspectorEvaluateSelection` mapping for this rather than expecting users to enter command line mode and type `call vimspector#Show......`. That way we shouldn't need to mess with the cursor.
___
*[autoload/vimspector.vim, line 535 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_95z-3yQSeQ1tAQR:-MSd_95z-3yQSeQ1tAQS:bwmem6p) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L535)):*
> ```vim
>   let lines = getbufline(bufnr('%'), start[0], end[0])
> 
>   if(len(lines) < 1)
> ```

no need for `(` here; `if len( lines ) < 1`
___
*[autoload/vimspector.vim, line 536 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_Enw1rC00DRrXpge:-MSd_Enw1rC00DRrXpgf:b-xjy2za) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L536)):*
> ```vim
> 
>   if(len(lines) < 1)
>     return
> ```

This function returns a value, so this return needs to return a value too.
___
*[autoload/vimspector.vim, line 541 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSda4Z93bMkSU-XQz09:-MSda4Z93bMkSU-XQz0A:b90nz2x) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L541)):*
> ```vim
>   " make sure the leave only the parts we care about if multiple lines are
>   " selected
>   let lines[0] = strcharpart(lines[0], start[1])
> ```

We need to have tests for:

* Single-line
* multi-line
* Unicode characters
* visual block selection
* visual line selection
___
*[autoload/vimspector.vim, line 562 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdcwUyA8RJ00O8sn-X:-MSdcwUyA8RJ00O8sn-Y:bww6d6r) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L562)):*
> ```vim
>   endif
> 
>   return py3eval('_vimspector_session.ShowTooltip(int( vim.eval( "winnr()" ) ) ,vim.eval( "expand(\"'.str.'\")" ), 0)')
> ```

80 characters

also, was surprised by the call to `expand()` here. what's the use case for that?
___
*[autoload/vimspector/internal/balloon.vim, line 51 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSddNOG-ONBQKB01v6N:-MSddNOG-ONBQKB01v6O:b8ftv6r) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L51)):*
> ```vim
> 
> function! vimspector#internal#balloon#Close() abort
>   if has('nvim')
> ```

I really dislike having `if has( 'nvim' )` all over the place.

Can we please put all neovim-specific code in a module named `neoballoon` and call the right one based on the already set up api_prefix ? Having all this conditional if neovim else vim stuff leads to a bit of spaghetti and makes me internally rage about the differences. 
___
*[autoload/vimspector/internal/balloon.vim, line 69 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdrH0A0iVfCfNdPwE-:-MSdrH0A0iVfCfNdPwE0:b9dnr43) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L69)):*
> ```
>   let top = '╭' . repeat('─',a:width + 2) . '╮'
>   let mid = '│' . repeat(' ',a:width + 2) . '│'
>   let bot = '╰' . repeat('─',a:width + 2) . '╯'
> ```

what happens with this border if `&ambiwidth` is 2 ?
___
*[autoload/vimspector/internal/balloon.vim, line 82 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnJ_y1J_T7ToMkojM:-MSdnJ_y1J_T7ToMkojN:b-q7zkn6) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L82)):*
> ```vim
>   endif
> 
>   noa call win_gotoid(s:float_win)
> ```

don't abbreviate vim commands in scripts. use `noautocommand` 

does neovim not have `win_execute` ?
___
*[autoload/vimspector/internal/balloon.vim, line 103 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnZIp5gDuQxX_mF72:-MSdnZIp5gDuQxX_mF73:bb7ravp) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L103)):*
> ```vim
> 
>   " resize the border window
>   let opts['width'] = width + 4
> ```

comments why 4 and 2 are used here (otherwise, look like magic numbers)
___
*[autoload/vimspector/internal/balloon.vim, line 123 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnwg-A75u54NwiEIN:-MSdnwg-A75u54NwiEIO:b2e4vb5) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L123)):*
> ```vim
>     call nvim_buf_set_lines(buf_id, 0, -1, v:true, vimspector#internal#balloon#nvim_generate_border(s:max_width, s:max_height))
> 
>     " default the dimensions for now. they can be easily overwritten later
> ```

does 'easily overwritten' mean that they _will_ be changed by the resize function? if so we should say that (otherwise, I'm not sure I understand the comment)
___
*[autoload/vimspector/internal/balloon.vim, line 154 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdolTTC_RDzyJ25TCL:-MSdolTTC_RDzyJ25TCM:bnfhz63) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L154)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     call nvim_win_set_option(s:float_win, 'wrap', v:false)
>     call nvim_win_set_option(s:float_win, 'cursorline', v:true)
>     call nvim [...]

2021-02-03 22:19 UTC, puremourning requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 1 of 3 files at r4, 1 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 40 unresolved discussions (waiting on @dsych)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdxdc96hZoW-jCZD4n:-MSdxdc96hZoW-jCZD4o:bm07vbq) (no related file):*
I think I would like to add  `<plug>` mappings for triggering the balloon, and add something to the `HUMAN` mode by default (at least in neovim). I think this feature is useful enough that it warrants a key, though we're running out of F-keys. Maybe we should just create the `<plug>` mapping and add a recommendation to map it manually ?

If not, then I think we should add an ex command like `VimspectorShowBalloon` rather than require users to `call vimspector#ShowBalloon( ... )`, which is not a good UX imo. YCM uses this code to take the visual selection when using `YcmCompleter Format`, which I think is a little neater than what we have below: https://github.com/ycm-core/YouCompleteMe/blob/master/python/ycm/vimsupport.py#L1226-L1251

---


<!-- Sent from Reviewable.io -->

2021-02-06 04:12 UTC, dsych reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 40 unresolved discussions (waiting on @dsych and @puremourning)

___
*[autoload/vimspector.vim, line 526 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdaGvT2bZg4lQRzMCQ:-MSpMJUL8HzC7N3rSD8O:b-y7mnht) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L526)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think a lot of this would be easier to write in Python. We can make a function in `utils.py`. Something like this " 

```
def GetVisualSelection():
  if vim.eval( 'mode()' ) != 'v':
    raise ValueError( "Only available in visual mode" )
  
  start_line, start_col = vim.current.buffer.mark( "'<" )
  end_line, end_col = vim.current.buffer.mark( "'>" )

  assert start_line >= end_line

  lines = vim.buffers[ bufnum ][ start_line : end_line + 1  ]
  lines[ 0 ] = lines[ 0 ][ start_pos : ]
  lines[ -1 ] = lines[ -1 ] : end_pos + 1 ]
```
</blockquote></details>

i mean we could, ofc, but i am not sure of the difference here, really. i am fine with it either way. if you want me to move it - i will.
___
*[autoload/vimspector.vim, line 530 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_O8P5rcbkJ4-ktJt:-MSpLSVF6Y1n-k2CLpjG:bliqk22) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L530)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I'm not sure about this. I think it would be  to create a `<plug>VimspectorEvaluateSelection` mapping for this rather than expecting users to enter command line mode and type `call vimspector#Show......`. That way we shouldn't need to mess with the cursor.
</blockquote></details>

if we do this route than we should be able to consolidate `showTooltip` and `showTooltipForSelection` into a single function, since mappings will not escape the visual selection mode. hence, we can directly check the current mode with `:h mode()` and there wont be any need to mess around with the cursor.
___
*[autoload/vimspector.vim, line 562 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdcwUyA8RJ00O8sn-X:-MSpXBLx9KNfaasL-rQP:beg1b4g) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L562)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

80 characters

also, was surprised by the call to `expand()` here. what's the use case for that?
</blockquote></details>

if `showTooltip` is called without arguments, we need to expand the value of `<cexpr>`, see the beginning of the function
___
*[autoload/vimspector/internal/balloon.vim, line 82 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnJ_y1J_T7ToMkojM:-MSpNCff3FMiqQvkmM-R:b-corgxl) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L82)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

don't abbreviate vim commands in scripts. use `noautocommand` 

does neovim not have `win_execute` ?
</blockquote></details>

unfortunately, nvim does not have `win_execute`
___
*[autoload/vimspector/internal/balloon.vim, line 123 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnwg-A75u54NwiEIN:-MSpNLyV4h0qkHW5xVzy:b-8dn1mk) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L123)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

does 'easily overwritten' mean that they _will_ be changed by the resize function? if so we should say that (otherwise, I'm not sure I understand the comment)
</blockquote></details>

this comment implies that the caller will manipulate the width after setting the content, since this function just sets some default content and dimensions.
in our case, the content is updated with `appendBuffer` and the dimensions are adjusted by the call to `vimspector#internal#balloon#nvim_resize_tooltip()` afterwards
___
*[autoload/vimspector/internal/balloon.vim, line 154 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdolTTC_RDzyJ25TCL:-MSpOPD2B0F9llEUYdGk:b-5q0aft) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L154)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> ```
>     call nvim_win_set_option(s:float_win, 'wrap', v:false)
>     call nvim_win_set_option(s:float_win, 'cursorline', v:true)
>     call nvim_win_set_option(s:float_win, 'signcolumn', 'no')
>     call nvim_win_set_option(s:float_win, 'relativenumber', v:false)
>     call nvim_win_set_option(s:float_win, 'number', v:false)
> ```

I feel like this exact set of options is used somewhere else, e.g. in `neopopup.vim`. can we consolidate/share the code there?
</blockquote></details>

i was not aware of it) but as far as i can tell, `neopopup.vim` only defines `wrap` and `singcolumn`. anyway it does not seems like they are functionally similar. The splash is not meant to be focused, hence it is missing some options, mainly `relativenumber`, `number`, `cursorline`. 
___
*[autoload/vimspector/internal/balloon.vim, line 171 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdpLuJ7H_r9v_BrF1-:-MSpQEvM45_9rPRhaHVb:bttt1nk) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L171)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

This is actually global scope function which could clash with any other, as it has no namespace. Let's move it to the top level and make it `vimspector#internal#balloon#_MouseFilter` (same for the others)

`function` not `func`
</blockquote></details>

i might be missing something, but isnt this function inside a closure? i am not able to reference it even after staring debugger with `:call MouseFilter()`
___
*[autoload/vimspector/internal/balloon.vim, line 181 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdpoD_BL7tb6yUMB5Z:-MSpQwT-EgKOcJK510dW:b-v016y2) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L181)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I'm not sure we need this function any more (other than in the neovim case).

We can just as well put `call popup_close( a:wind )` here.
</blockquote></details>

true, but i thought it would bring a little more uniformity. 
___
*[autoload/vimspector/internal/balloon.vim, line 190 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdq1eoA7Vkx0xI1H88:-MSpRAY49BdFKgk7hQQB:bhkrtsn) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L190)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this comment is not really useful. I'm not sure what it means about "focus the correct window", but I think we want to just say something like "Explicitly pass the buffer/line/col to ExpandVariable, as the current window is not the popup"
</blockquote></details>

this comment talks about the fact that python does not have the reference to popup window inside `vim.windows` variable. in fact, there is no other way i am aware of how to retrieve the popup's window id. hence, we cant just do what the old python code did: getting the cursor li [...]

2021-02-06 20:54 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 36 unresolved discussions (waiting on @dsych and @puremourning)

___
*[autoload/vimspector.vim, line 526 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdaGvT2bZg4lQRzMCQ:-MSt3aCOE_sLdhGkYD2Y:b-den4lx) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L526)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i mean we could, ofc, but i am not sure of the difference here, really. i am fine with it either way. if you want me to move it - i will.
</blockquote></details>

I think I prefer it in the python code. that's more in line with the general style of the project.
___
*[autoload/vimspector.vim, line 530 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_O8P5rcbkJ4-ktJt:-MSt3lC-Ajql30M0QmUI:b-8m3dx4) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L530)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

if we do this route than we should be able to consolidate `showTooltip` and `showTooltipForSelection` into a single function, since mappings will not escape the visual selection mode. hence, we can directly check the current mode with `:h mode()` and there wont be any need to mess around with the cursor.
</blockquote></details>

that all sounds win win win to me
___
*[autoload/vimspector.vim, line 562 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdcwUyA8RJ00O8sn-X:-MSt3tR_2fnbPBAPRBDU:b-skvd66) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L562)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

if `showTooltip` is called without arguments, we need to expand the value of `<cexpr>`, see the beginning of the function
</blockquote></details>

oh right, this is better then I think:

```
if a:0 > 0
  let str = a:1
else
  let str = expand( '<cexpr>' )
endif
```
___
*[autoload/vimspector/internal/balloon.vim, line 123 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdnwg-A75u54NwiEIN:-MSt49nI1t5kzU1uE6_O:b-t43jzg) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L123)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

this comment implies that the caller will manipulate the width after setting the content, since this function just sets some default content and dimensions.
in our case, the content is updated with `appendBuffer` and the dimensions are adjusted by the call to `vimspector#internal#balloon#nvim_resize_tooltip()` afterwards
</blockquote></details>

let's write that more precisely then. i.e. something like "We just set some default dimentions here, and we update them later with a call to resize_tooltip"
___
*[autoload/vimspector/internal/balloon.vim, line 154 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdolTTC_RDzyJ25TCL:-MSt4MCA9mn57vaHHjFy:bb87ghg) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L154)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i was not aware of it) but as far as i can tell, `neopopup.vim` only defines `wrap` and `singcolumn`. anyway it does not seems like they are functionally similar. The splash is not meant to be focused, hence it is missing some options, mainly `relativenumber`, `number`, `cursorline`. 
</blockquote></details>

ok sure
___
*[autoload/vimspector/internal/balloon.vim, line 171 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdpLuJ7H_r9v_BrF1-:-MSt4SsTCGAgTOxP2FV4:bg68ct6) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L171)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i might be missing something, but isnt this function inside a closure? i am not able to reference it even after staring debugger with `:call MouseFilter()`
</blockquote></details>

perhaps it's me that's missing something, but my experience differs:

![Screenshot 2021-02-06 at 20.46.10.png](https://files.reviewableusercontent.io/images/reviewable/10584846/2EzmtsXYXWlthWBbV3IPRId7/Screenshot%202021-02-06%20at%2020.46.10.png)

![Screenshot 2021-02-06 at 20.47.38.png](https://files.reviewableusercontent.io/images/reviewable/10584846/tjyrTdpQwYMKNnOLqyW-OCo8/Screenshot%202021-02-06%20at%2020.47.38.png)
___
*[autoload/vimspector/internal/balloon.vim, line 190 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdq1eoA7Vkx0xI1H88:-MSt5_8L6C-u_ecJxxY_:b-l3s7cl) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L190)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

this comment talks about the fact that python does not have the reference to popup window inside `vim.windows` variable. in fact, there is no other way i am aware of how to retrieve the popup's window id. hence, we cant just do what the old python code did: getting the cursor line of the current window because it will return the line from window that opened the popup! so we need to manually pass the line number from here
</blockquote></details>

sure, I think we can update the comment to be more clear about the why. both my version and your explanation are unambiguous.
___
*[python3/vimspector/utils.py, line 639 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSds7og-XwNzLMjD4rM:-MSt5vMe6wpPlvRHgPhV:bnc1zsf) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/utils.py#L639)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i think it is still relevant because the same code path will be executed by `HoverTooltip` (used as callback for `balloonevalexpr`), which ultimately calls into this function.
</blockquote></details>

right. I noticed that only _after_ I wrote this comment. my bad.
___
*[python3/vimspector/variables.py, line 288 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdtVxj7pQ620fR1njH:-MSt6-tO9xV8L2UJSfFt:b4urtm3) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/variables.py#L288)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

as i mentioned before,  dont want to mix balloon terminology with popup, since they are different things; nvim does not even have it! i am open to a different name, but please not balloon related
</blockquote></details>

IMO it's still a balloon because:

- it does the same job as the built-in balloon (as in balloon_show)
- it bridges the missing balloon functionality from neovim
- in vim it's used in `balloonexpr` and `popup_beval`

I like balloon because it describes the functionality (i.e. a popup associated with the current context). I sort-of agree that tooltip is a similar connotation, but when I hear tooltip, I think like context-sensitive help, not structured data.


<!-- Sent from Reviewable.io -->

2021-02-20 05:15 UTC, dsych reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: 2 of 8 files reviewed, 36 unresolved discussions (waiting on @dsych and @puremourning)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdwmA-5EggMupJlmF6:-MSyRG0xCyHw7xvoEu8R:b-896fix) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

let's remove dead code for the old ballloon eval
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdxdc96hZoW-jCZD4n:-MTxkOu4Aoc1JW7rkMfU:b8ifxdq) (no related file):*
done, i united everything under a single `<Plug>VimspectorBalloonEval`, which is a one stop shop for single variable eval, selection eval and hover eval.
note about selection eval, i tried all 3 types and here are the results:
1. normal selection works as expected
2. line vise selection works as expected, it evaluates the entire line(s)...
3. block vise selection works as expected for a single line eval. **however** for multi line evaluation, it will evaluate **everything between selection marks**. this behaviour is similar to regular selection. i dont think it makes sense to keep tweaking this one, since who would be evaluating in block mode anyway. i dont like make assumptions like this, but we have to realistic... 

> please take a look at my current approach and greenlight it before i start implementing tests

---
___
*[autoload/vimspector.vim, line 526 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdaGvT2bZg4lQRzMCQ:-MTxjFfM7LnjghmxbhcC:b-eueoe4) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L526)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I think I prefer it in the python code. that's more in line with the general style of the project.
</blockquote></details>

done. implemented `utils.GetVisualSelection`
___
*[autoload/vimspector.vim, line 530 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_O8P5rcbkJ4-ktJt:-MTxn-nmBjRJrMTum0_x:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L530)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

that all sounds win win win to me
</blockquote></details>

Done.
___
*[autoload/vimspector.vim, line 535 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_95z-3yQSeQ1tAQR:-MTxmXb95_V3hfGqaeDH:b-el8pr8) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L535)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

no need for `(` here; `if len( lines ) < 1`
</blockquote></details>

moved this functionality to python
___
*[autoload/vimspector.vim, line 536 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSd_Enw1rC00DRrXpge:-MTxm_bc3YzOPg8ZrR2o:b-b6d7gw) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L536)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

This function returns a value, so this return needs to return a value too.
</blockquote></details>

not relevant anymore
___
*[autoload/vimspector.vim, line 562 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdcwUyA8RJ00O8sn-X:-MTxmxPe93kZGETuc-0l:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector.vim#L562)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

oh right, this is better then I think:

```
if a:0 > 0
  let str = a:1
else
  let str = expand( '<cexpr>' )
endif
```
</blockquote></details>

Done.
___
*[autoload/vimspector/internal/balloon.vim, line 167 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdozpO23_E09bYI2Db:-MTxqz6Z7-SsyEq47qjg:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L167)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

I'm not sure about this `WinLeave *` - is there a way to make it a `<buffer>` autocmd so that we don't get unexpected results, such as https://github.com/neovim/neovim/issues/13721. Dunno if that will really fix the bug, but it feels more targeted scope for the autocommand at least
</blockquote></details>

Done.
___
*[autoload/vimspector/internal/balloon.vim, line 171 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdpLuJ7H_r9v_BrF1-:-MTxn5ik9ZvBGDDl0zYf:b-8299ff) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L171)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

perhaps it's me that's missing something, but my experience differs:

![Screenshot 2021-02-06 at 20.46.10.png](https://files.reviewableusercontent.io/images/reviewable/10584846/2EzmtsXYXWlthWBbV3IPRId7/Screenshot%202021-02-06%20at%2020.46.10.png)

![Screenshot 2021-02-06 at 20.47.38.png](https://files.reviewableusercontent.io/images/reviewable/10584846/tjyrTdpQwYMKNnOLqyW-OCo8/Screenshot%202021-02-06%20at%2020.47.38.png)

</blockquote></details>

you are right, i forgot to eval the function that defines the closure. fixed
___
*[autoload/vimspector/internal/balloon.vim, line 199 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdqXP-3JnO2QTIwsvZ:-MTxoCtj0qUh9qX5brA5:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L199)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

ditto here - this should be a top-level autoload function I think
</blockquote></details>

Done.
___
*[python3/vimspector/debug_session.py, line 543 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdrUBF7YOpojpM2H3i:-MTxoAiVCD8m3mDl_FB6:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/debug_session.py#L543)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Any reason this is called `ShowTooltip` rather than replacing `ShowBalloon` ?

I don't think that `ShowBalloon` is used anymore. 
</blockquote></details>

Done.
___
*[python3/vimspector/variables.py, line 288 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdtVxj7pQ620fR1njH:-MTxnc3e9dBn7J7ihnGH:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/variables.py#L288)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

IMO it's still a balloon because:

- it does the same job as the built-in balloon (as in balloon_show)
- it bridges the missing balloon functionality from neovim
- in vim it's used in `balloonexpr` and `popup_beval`

I like balloon because it describes the functionality (i.e. a popup associated with the current context). I sort-of agree that tooltip is a similar connotation, but when I hear tooltip, I think like context-sensitive help, not structured data.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-20 05:27 UTC, dsych reviewed
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: 2 of 8 files reviewed, 36 unresolved discussions (waiting on @dsych and @puremourning)

___
*[autoload/vimspector/internal/balloon.vim, line 212 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdqwVEB8r7ZofKuINu:-MTxrmWE5U1NkiNI4PDf:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L212)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

can we use `s:popup_win_id` for this as that seems more vim like, and specific that it's a winid not, say a window number or something else. wdyt?
</blockquote></details>

Done.
___
*[python3/vimspector/utils.py, line 643 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdsCwg-pga4QfeCY0J:-MTxrzLx9ELuaiQHiyzm:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/utils.py#L643)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

use a proper variable name (`rc` could mean anything) if the value is a window id, call it `window_id`
</blockquote></details>

Done.
___
*[python3/vimspector/utils.py, line 649 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdt5lg69xAFmQhj8UX:-MTxs1sH4aVMDHVRAh6i:blzr9jw) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/utils.py#L649)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

seems strange that this has to be called from here. couldn't the vimscript code `CreateTooltip` above (which I think should be called `ShowBalloon`) just call it ?
</blockquote></details>

i though i to be logical: above popup is populated with new content and here we re-adjust the window size accordingly
___
*[python3/vimspector/variables.py, line 141 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdsUIr2ZjxR0JWo7Lb:-MTxsP5E4l3eEXFSKOxk:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/variables.py#L141)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

remove extraneous parentheses
</blockquote></details>

Done.
___
*[python3/vimspector/variables.py, line 311 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdu7v-09ZhrNc6j4Mq:-MTxt7MXA0Llof_RCu-l:b-896fix) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/variables.py#L311)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

does this really need to return `''` ?
</blockquote></details>

Done.
___
*[python3/vimspector/variables.py, line 377 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSduBrH-k86n4v0lRK_:-MTxtez19mO3BRQgNSaC:b-fjyhwi) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/variables.py#L377)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this function always returns `''`, so no need for it to return anything.
</blockquote></details>

this is required, since the same method is called for mouse hover and it requires a return


<!-- Sent from Reviewable.io -->

2021-02-20 12:32 UTC, puremourning commented
Thanks for the updates ! I’ll try and take a look at this later today. 

Regarding visual block mode, 100% agree, it’s an edge case so any vaguely sane behaviour is fine. Thanks for the notes on that.

2021-02-20 20:53 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: 2 of 8 files reviewed, 33 unresolved discussions (waiting on @dsych and @puremourning)

___
*[README.md, line 263 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU08a7492QMODtKT82G:-MU08a7492QMODtKT82H:b2i8ufh) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/README.md#L263)):*
> ```Markdown
>   and [`:VimspectorWatch`](#watches)
> * Functions - There are
>   [`:call vimspector#ShowTooltip()`](#variable-or-selection-hover-evaluation) and
> ```

I think this needs updating with the new approach?
___
*[autoload/vimspector.vim, line 528 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU08kVJADSG89XoDIG3:-MU08kVJADSG89XoDIG4:b587ty) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector.vim#L528)):*
> ```vim
> function! vimspector#ShowEvalBalloon( is_visual ) abort
>   if a:is_visual
>     let expr = py3eval( '__import__( "vimspector", fromlist = [ "utils" ] ).utils.GetVisualSelection( int( vim.eval( "winbufnr( winnr() )" ) ) )' )
> ```

80 chars 
___
*[autoload/vimspector.vim, line 529 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU08vZi9bYslud_9wBL:-MU08vZi9bYslud_9wBM:bwarzkk) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector.vim#L529)):*
> ```vim
>   if a:is_visual
>     let expr = py3eval( '__import__( "vimspector", fromlist = [ "utils" ] ).utils.GetVisualSelection( int( vim.eval( "winbufnr( winnr() )" ) ) )' )
>     let expr = join(expr)
> ```

spaces inside parens

I thinkg if we should really join it here with `\n` ( `let expr = join( expr, "\n" )` - so that newlines are preserved for languages where that matters (like python, tcl, etc.)
___
*[autoload/vimspector.vim, line 531 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU08zLtAf7G489O0-W6:-MU08zLtAf7G489O0-W7:b-t3lash) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector.vim#L531)):*
> ```vim
>     let expr = join(expr)
>   else
>     let expr = expand('<cexpr>')
> ```

spaces inside parens
___
*[autoload/vimspector.vim, line 534 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU09_QS0lY4TiEz9bMK:-MU09_QS0lY4TiEz9bML:bgp9l1b) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector.vim#L534)):*
> ```vim
>   endif
> 
>   return py3eval( '_vimspector_session.ShowEvalBalloon( int( vim.eval( "winnr()" ) ), "'.expr.'", 0 )' )
> ```

spaces around `.` concatenation operator, 80 characters
___
*[autoload/vimspector/internal/balloon.vim, line 167 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdozpO23_E09bYI2Db:-MU0AydGEkpmgYuh56Cm:bwc0sph) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L167)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this is still a BufLeave for _all_ buffers. I was expecting this do become something like `autocmd <buffer> WinLeave * :call ....` - which would mean that it applies after leaving the window containing the current buffer (which is always the special eval balloon buffer). Changing to just `BufLeave *` is not all that much of a change in practice from WinLeave.
___
*[autoload/vimspector/internal/balloon.vim, line 212 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdqwVEB8r7ZofKuINu:-MU0BaMO-zESA_eAsGDD:bka7crq) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/autoload/vimspector/internal/balloon.vim#L212)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see `float_win`
___
*[autoload/vimspector/internal/balloon.vim, line 22 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU09xo_1hWoSF54QN1l:-MU09xo_1hWoSF54QN1m:b-7lspgm) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector/internal/balloon.vim#L22)):*
> ```vim
> " }}}
> 
> scriptencoding utf-8
> ```

Throughout this file:

- spaces inside `(`/`)` and `[`/`]`
- 80 character limit
- spaces around operators (particularly `.` operator)

I keep meaning to make `vint` able to do style checks, but it's not really designed for that unfortunately.
___
*[autoload/vimspector/internal/balloon.vim, line 25 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU09hvU-6clSHDzJFw6:-MU09hvU-6clSHDzJFw7:b48ai14) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/autoload/vimspector/internal/balloon.vim#L25)):*
> ```vim
> 
> function! vimspector#internal#balloon#HoverTooltip() abort
>   return py3eval('_vimspector_session.ShowEvalBalloon(int( vim.eval( "v:beval_winnr" ) ) + 1 ,vim.eval( "v:beval_text"), 1)')
> ```

80 characters, spaces inside parentheses
___
*[plugin/vimspector.vim, line 64 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU0BgN360VLWKUCe37y:-MU0BgN360VLWKUCe37z:b-9xior6) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/plugin/vimspector.vim#L64)):*
> ```vim
> 
> nnoremap <silent> <Plug>VimspectorBalloonEval
>       \ :<c-u>call vimspector#ShowEvalBalloon(0)<CR>
> ```

spaces inside `(` -> `( 0 )`
___
*[plugin/vimspector.vim, line 67 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU0BiZP3cI9GVJHT7r-:-MU0BiZP3cI9GVJHT7r0:bw8ras) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/plugin/vimspector.vim#L67)):*
> ```vim
> 
> xnoremap <silent> <Plug>VimspectorBalloonEval
>       \ :<c-u>call vimspector#ShowEvalBalloon(1)<CR>
> ```

`(1)` -> `( 1 )`
___
*[python3/vimspector/debug_session.py, line 705 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdsiqH42AIFihtvtOb:-MU0ByJP9T6nrzD20piL:byaladt) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/debug_session.py#L705)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i did not want to use balloon, since it is not really using the balloon functionality. but i agree about the name being too generic. i am open to suggestions
</blockquote></details>

I like your choice of `EvalBalloon` elsewhere - let's use that everywhere
___
*[python3/vimspector/debug_session.py, line 561 at r7](https://reviewable.io/reviews/puremourning/vimspector/316#-MU0BubW3cHTkbN77ZO-:-MU0BubW3cHTkbN77ZO0:bnhc10q) ([raw file](https://github.com/puremourning/vimspector/blob/42b4520c5240e93a84f5f345594a7eaddedac22a/python3/vimspector/debug_session.py#L561)):*
> ```Python
> 
> 
>   def _CleanUpTooltip( self ):
> ```

Should this now be `CleanUpEvalBalloon`
___
*[python3/vimspector/utils.py, line 649 at r6](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdt5lg69xAFmQhj8UX:-MU0CFwfBcPq-jJmv0O1:buzz4lq) ([raw file](https://github.com/puremourning/vimspector/blob/86a62850358e595ed3ccf5718de5d8d95835d8a8/python3/vimspector/utils.py#L649)):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

i though i to be logical: above popup is populated with new content and here we re-adjust the window size accordingly
</blockquote></details>

but is there any time when we would call `CreateTooltip` but not also call `nnvim_resize_tooltip` ? If so then the separation in this case is artificial and a bug factory (in case these calls become separated)
___
*[python3/vimspector/utils.py, line 732 at r7](https://reviewable.io/reviews/puremourning/vi [...]

2021-02-20 20:53 UTC, puremourning reviewed
> Reviewed 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 33 unresolved discussions (waiting on @dsych and @puremourning)



<!-- Sent from Reviewable.io -->

2021-02-21 15:59 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 33 unresolved discussions (waiting on @dsych and @puremourning)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdxdc96hZoW-jCZD4n:-MU4Iipd0yq8iV3MnUk8:bki4pje) (no related file):*
<details><summary><i>Previously, dsych (Dmytro Sych) wrote…</i></summary><blockquote>

done, i united everything under a single `<Plug>VimspectorBalloonEval`, which is a one stop shop for single variable eval, selection eval and hover eval.
note about selection eval, i tried all 3 types and here are the results:
1. normal selection works as expected
2. line vise selection works as expected, it evaluates the entire line(s)...
3. block vise selection works as expected for a single line eval. **however** for multi line evaluation, it will evaluate **everything between selection marks**. this behaviour is similar to regular selection. i dont think it makes sense to keep tweaking this one, since who would be evaluating in block mode anyway. i dont like make assumptions like this, but we have to realistic... 

> please take a look at my current approach and greenlight it before i start implementing tests
</blockquote></details>

Thanks again for this great contribution. I realise a lot of my comments are now in the sort of "bike shed" region and pertain to things like style and such. I also realise this can be a tedious ask to rework, so I've gone ahead and done some of the rework myself and fixed a couple of issues too after doing some more testing. here's the commit: https://github.com/puremourning/vimspector/commit/5d25ea03fcec30a956c21c3f65b83b2d9418f98d

---


<!-- Sent from Reviewable.io -->

2021-02-21 16:27 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)* status: all files reviewed, 33 unresolved discussions (waiting on @dsych and @puremourning)

*[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdxdc96hZoW-jCZD4n:-MU4Pgd38SJDwAQcpDI0:b-sui3mt) (no related file):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Thanks again for this great contribution. I realise a lot of my comments are now in the sort of "bike shed" region and pertain to things like style and such. I also realise this can be a tedious ask to rework, so I've gone ahead and done some of the rework myself and fixed a couple of issues too after doing some more testing. here's the commit: https://github.com/puremourning/vimspector/commit/5d25ea03fcec30a956c21c3f65b83b2d9418f98d
</blockquote></details>

And I fixed the test too https://github.com/puremourning/vimspector/commit/80dcf46379b4f7299c680f2e456aade925945c9c

---


<!-- Sent from Reviewable.io -->

2021-02-21 17:16 UTC, dsych commented
> > _[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/316)_ status: all files reviewed, 33 unresolved discussions (waiting on @dsych and @puremourning)
> 
> _[a discussion](https://reviewable.io/reviews/puremourning/vimspector/316#-MSdxdc96hZoW-jCZD4n:-MU4Iipd0yq8iV3MnUk8:bki4pje) (no related file):_
> Previously, dsych (Dmytro Sych) wrote…
> 
> Thanks again for this great contribution. I realise a lot of my comments are now in the sort of "bike shed" region and pertain to things like style and such. I also realise this can be a tedious ask to rework, so I've gone ahead and done some of the rework myself and fixed a couple of issues too after doing some more testing. here's the commit: [5d25ea0](https://github.com/puremourning/vimspector/commit/5d25ea03fcec30a956c21c3f65b83b2d9418f98d)

Oh wow, thanks for taking care of it! It did take me some willpower to come back to this pr)
I see that you opened another clean pr, so I am going to close this one.

2021-02-21 17:16 UTC, closed without merging