Open fold when jumping to a frame
puremourning/vimspector pull request #733
Opened 2023-03-21 02:03 UTC by timsu92

This simply do a `zv` after successfully setting cursor in position.
`zv` requires `+folding` to be enabled in Vim, which is one of the features of Vim huge build, and it's a requirement stated in README.

fix: 679

2023-03-21 02:03 UTC, puremourning commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/puremourning/vimspector/733)
<!-- Reviewable:end -->

2023-03-21 07:29 UTC, puremourning requested changes
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/733)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @timsu92)

___
*[`python3/vimspector/code.py` line 159 at r1](https://reviewable.io/reviews/puremourning/vimspector/733#-NR23Z8TEuZnn9a1sFjm:-NR23Z8TEuZnn9a1sFjn:bh5o51o) ([raw file](https://github.com/puremourning/vimspector/blob/b69781921497aa2c4fba5aa4a84dd4f56e064b87/python3/vimspector/code.py#L159)):*
> ```Python
>       return False
> 
>     vim.command( 'normal zv' )
> ```

Shouldn’t we use normal! To avoid mappings?


<!-- Sent from Reviewable.io -->

2023-03-22 02:18 UTC, timsu92 commented
Nice catch!

2023-03-23 07:54 UTC, puremourning approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/puremourning/vimspector/733#-:-NRCSX9X7VrjneivUalz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @timsu92)



<!-- Sent from Reviewable.io -->

2023-03-23 07:55 UTC, merged